### ISSUE TITLE
Add Payload to reducer

### ISSUE THREAD

**Issue by chrismagri** [KarlPurk/redux-decorators#8]
As it is right now the only way to use the action is by 
```
class MyReducers {
    @Reducer() add(state): { return { count: state.count + 1; } }
}
```

An idea that i have on how to make this better is doing something like:

```
class MyReducers {
    @Reducer() add(state, action): { console.log(action.payload) }
}
```

What do you think?

**Comment by KarlPurk** [comment]
Currently the only way to access the action is through the root reducer.  This would be a nice  improvement to action reducers.  Nice suggestion :+1:

**Comment by KarlPurk** [comment]
Okay I've looked into this a little and I'm not sure this is required.  Let's look at an example, let's say we dispatch this action:

```
dispatch('addPost', 'My title', 'My body text');
```

The action is automatically created for you, and follows a predetermined pattern.  This means when the action reducer is called it's passed the state and any other data attached to the action.  For example the above action passes the `title` and `body` values to the action reducer:

```
@Reducer() addPost(state, title, body): {
  // we are passed the title and body as arguments
}
```

So although you can't access the action, there's really no need to because you can't attach anything to the action.  

Does this resolve your issue?

**Comment by KarlPurk** [comment]
I'm assuming this is resolved.
